# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow manually
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    permissions:
      packages: write
      contents: read
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Downloads WexFlow Latest
      - uses: robinraju/release-downloader@v1
        with:
            # The source repository path.
            # Expected format {owner}/{repo}
            # Default: ${{ github.repository }}
            repository: 'aelassas/wexflow'

            # A flag to set the download target as latest release
            # The default value is 'false'
            latest: true

            # A flag to download from prerelease. It should be combined with latest flag.
            # The default value is 'false'
            preRelease: false

            # The github tag. e.g: v1.0.1
            # Download assets from a specific tag/version
            # tag: ''

            # The release id to download files from
            # releaseId: ''

            # The name of the file to download.
            # Use this field only to specify filenames other than tarball or zipball, if any.
            # Supports wildcard pattern (eg: '*', '*.deb', '*.zip' etc..)
            fileName: 'wexflow-*-linux-netcore.zip'

            # Download the attached tarball (*.tar.gz)
            tarBall: false

            # Download the attached zipball (*.zip)
            zipBall: false

            # Relative path under $GITHUB_WORKSPACE to place the downloaded file(s)
            # It will create the target directory automatically if not present
            # eg: out-file-path: "my-downloads" => It will create directory $GITHUB_WORKSPACE/my-downloads
            out-file-path: ''

            # A flag to set if the downloaded assets are archives and should be extracted
            # Checks all downloaded files if they end with zip, tar or tar.gz and extracts them, if true.
            # Prints a warning if enabled but file is not an archive - but does not fail.
            extract: true

            # Github access token to download files from private repositories
            # https://docs.github.com/en/actions/configuring-and-managing-workflows/creating-and-storing-encrypted-secrets
            # eg: token: ${{ secrets.MY_TOKEN }}
            # token: ''

            # The URL of the Github API, only use this input if you are using Github Enterprise
            # Default: "https://api.github.com"
            # Use http(s)://[hostname]/api/v3 to access the API for GitHub Enterprise Server
            # github-api-url: ''
      # Check what files are present
      - run: ln -s ./wexflow ./WorkflowEngine/wexflow
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
#      - name: Login to Docker Hub
#        uses: docker/login-action@v3
#        with:
#          username: ${{ vars.DOCKERHUB_USERNAME }}
#          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./WexflowEngine
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/mwgevans/mywexflowengine:latest
            ghcr.io/mwgevans/mywexflowengine:1.0.0     
 #           user/app:latest
 #           user/app:1.0.0




            
      # Check what files are present
      - run: ls -l wexflow

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
